name: switcher_comunicaciones
description: Switcher y Servidor para las cámaras de Comunicaciones.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.41
  google_fonts: ^5.1.0
  provider: ^6.0.5
  go_router: ^10.1.2
  dart_frog: ^1.0.1
  web_socket_channel: ^2.4.0
  shelf: ^1.1.3
  shelf_web_socket: ^1.0.4
  get_ip_address: ^0.0.6
  wifi_ip_details: ^1.0.0
  shelf_router: ^1.1.4
  shelf_plus: ^1.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/videos/
